language: node_js
node_js:
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
   - LD_PRELOAD="" /usr/bin/Xvfb -extension RANDR -nolisten tcp -extension GLX :99
branches:
  only:
    - master
